on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-service-images:
    strategy:
      matrix:
        service: 
          - { name: newsletter, image_name: "lukaskarelat-newsletter", image_description: ""}
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      service: ${{matrix.service.name}}
      image_name: ${{matrix.service.image_name}}
      image_description: ${{matrix.service.image_description}}
        